spring.application.name=product-service

server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/productdb
spring.data.mongodb.database=productdb

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=product-group


